README.md
=> Project Setting

Team meeting/Meeting 2018-02-22.txt, Team meeting/Minutes of team meeting 2018-02-15.txt, Team meeting/Minutes of team meeting 2018-03-01.txt
=> add Mar/1 meeting and previous ones(dicebattle) too

man.js
=> Man functionality

goHomeBulls.html, stamina.js
=> Basic Stamina in HTML

Team meeting/Minutes of team meeting 2018-03-08.txt
=> Team meeting 2018-03-08

maps.js
=> commit maps.js

Team meeting/Minutes of team meeting 2018-03-15.txt
=> 03-15 Meeting

goHomeBulls.html, main.js, scene_factory.js, stamina.js, utils.js
=> After Spring break release

stamina.js
=> change decrease rate

game.js, scene/scene_editor.js, scene/scene_main.js, scene/scene_title.js
=> commit scene and game

main.js, stamina.js, utils.js
=> comments on my code

README.md, stamina.js
=> How to run

README.md
=> youtube video link added

README.md, stamina.js
#45 
Merge to master (Add youtube link)
=> Merge to master (Add youtube link)

README.md
=> add chrome to readme

README.md
=> Merge to master (add "use chrome")

Team meeting/Minutes of team meeting 2018-03-29.txt, goHomeBulls.html
=> Team meeting 03-29

scene/scene_main.js, stamina.js
=> stamina bug fixed

.idea/goHomeBulls.iml, .idea/modules.xml, .idea/vcs.xml, HallOfFame.html, goHomeBulls.html
=> Hall of fame page created

HallOfFame.html, goHomeBulls.html, maps.js, server.js, stamina.js
=> fixed error Halloffame

goHomeBulls.html
=> Pull request to my branch

StaminaShop.html, goHomeBulls.html, scene/scene_main.js, stamina.js
=> almost finish shopping system

man.js
=> re-submit applying traps and map

README.md, StaminaShop.html, index.html, scene/scene_main.js
=> Beta release (stamina bug fixed)

README.md
=> change youtube link

index.html
=> youtube link on landing page

README.md, index.html
#114 
Merge to master for alpha release
youtube link on landing page
=> Merge to master

README.md
=> update readme to secure link

goHomeBulls.html, scene/scene_main.js
Create a Rank System which display in the top right corner
=> Finished Help Wanted Issue

scene/scene_main.js
=> Modified refresh function

scene/scene_main.js, stamina.js
=> Enhancement(uppercase and reset when lack of stamina)

goHomeBulls.html
=> Change Hall of fame

goHomeBulls.html
=>  change stanmina shop button style

goHomeBulls.html
#184 Combine 3 music files together into one mp3 file
=> Add different musics throughout the game

goHomeBulls.html
=> Fixed the front problem

goHomeBulls.html
=> Fixed the hall of fame

goHomeBulls.html
=> Updated the official Release

README.md, Team meeting/Minutesofteammeeting2018-05-03.txt
=> Official release README update
